# Generated by Django 5.0.6 on 2024-07-30 16:29

import account.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nfc_uid', models.CharField(blank=True, null=True, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=3)),
                ('phone2', models.CharField(max_length=4)),
                ('phone3', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('detail_address', models.CharField(max_length=255)),
                ('nickname', models.CharField(default='', max_length=100, unique=True)),
                ('user_image', models.ImageField(default='default.png', null=True, upload_to='user_image')),
                ('birth', models.DateField()),
                ('usertype', models.IntegerField(choices=[(0, 'Owner'), (1, 'Trainer'), (2, 'Member')], default=2)),
                ('gender', models.CharField(choices=[('0', 'Man'), ('1', 'Woman')], max_length=1)),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('gym_entry_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gym_manual_exit_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('manual_exit_rate', models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.UUIDField(default=uuid.uuid4)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
