# Generated by Django 5.0.6 on 2024-07-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.IntegerField(choices=[(0, 'Owner'), (1, 'Trainer'), (2, 'Member')], default=2),
        ),
    ]
