# Generated by Django 5.0.6 on 2024-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nfc_uid',
            field=models.CharField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(default='default.png', null=True, upload_to='user_image'),
        ),
    ]
