# Generated by Django 5.0.3 on 2024-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateField(),
        ),
    ]
