# Generated by Django 5.0.3 on 2024-07-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
