# Generated by Django 5.0.3 on 2024-07-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
