# Generated by Django 5.0.3 on 2024-07-24 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone1',
            field=models.CharField(default=1, max_length=3, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'OOO-OOOO-OOOO'.", regex='^\\d{3}-\\d{4}-\\d{4}$')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone2',
            field=models.CharField(default=1, max_length=4, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'OOO-OOOO-OOOO'.", regex='^\\d{3}-\\d{4}-\\d{4}$')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone3',
            field=models.CharField(default=1, max_length=4, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'OOO-OOOO-OOOO'.", regex='^\\d{3}-\\d{4}-\\d{4}$')]),
            preserve_default=True,
        ),
    ]
