# Generated by Django 5.0.3 on 2024-07-24 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_phone1_alter_customuser_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone3',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.UUIDField(default=uuid.uuid4)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
