# Generated by Django 5.0.3 on 2024-07-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_customuser_username'),
        ('account', '0015_alter_customuser_phone1_alter_customuser_phone2_and_more'),
    ]

    operations = [
    ]
