# Generated by Django 5.0.6 on 2024-07-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentreservation',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
