# Generated by Django 5.0.6 on 2024-07-09 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('gym_id', models.AutoField(primary_key=True, serialize=False)),
                ('gym_name', models.CharField(max_length=100)),
                ('gym_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateField()),
                ('membership_type', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('recent_joined_date', models.DateField()),
                ('recent_membership', models.CharField(max_length=100)),
                ('recent_expiry', models.DateField()),
                ('renewal_status', models.BooleanField(default=False)),
                ('renewal_count', models.IntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.owner'),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100, null=True)),
                ('trainer_image', models.ImageField(null=True, upload_to='trainer_images')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gym')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.owner')),
            ],
        ),
        migrations.CreateModel(
            name='PT',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('pt_end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gymmember')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('personal_if', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('medical_conditions', models.TextField()),
                ('medications', models.TextField()),
                ('frequency', models.IntegerField()),
                ('types', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=50)),
                ('goals', models.CharField(max_length=255)),
                ('diet_habits', models.TextField()),
                ('sleep_pattern', models.CharField(max_length=50)),
                ('stress_level', models.CharField(max_length=50)),
                ('smoking', models.BooleanField()),
                ('smoking_amount', models.IntegerField(blank=True, null=True)),
                ('drinking', models.BooleanField()),
                ('drinking_amount', models.IntegerField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField()),
                ('muscle_mass', models.FloatField()),
                ('basal_metabolic_rate', models.FloatField()),
                ('bmi', models.FloatField()),
                ('short_term_goals', models.TextField()),
                ('long_term_goals', models.TextField()),
                ('preferred_exercise_types', models.CharField(max_length=255)),
                ('available_times', models.CharField(max_length=255)),
                ('gym_member_if', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gyms.gymmember')),
            ],
        ),
    ]