# Generated by Django 5.0.6 on 2024-07-11 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('personal_if', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('medical_conditions', models.TextField()),
                ('medications', models.TextField()),
                ('frequency', models.IntegerField()),
                ('types', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=50)),
                ('goals', models.CharField(max_length=255)),
                ('diet_habits', models.TextField()),
                ('sleep_pattern', models.CharField(max_length=50)),
                ('stress_level', models.CharField(max_length=50)),
                ('smoking', models.BooleanField()),
                ('smoking_amount', models.IntegerField(blank=True, null=True)),
                ('drinking', models.BooleanField()),
                ('drinking_amount', models.IntegerField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField()),
                ('muscle_mass', models.FloatField()),
                ('basal_metabolic_rate', models.FloatField()),
                ('bmi', models.FloatField()),
                ('short_term_goals', models.TextField()),
                ('long_term_goals', models.TextField()),
                ('preferred_exercise_types', models.CharField(max_length=255)),
                ('available_times', models.CharField(max_length=255)),
                ('gym_member_if', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gyms.gymmember')),
            ],
        ),
    ]
