# Generated by Django 5.0.6 on 2024-07-12 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_personalinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='owner',
        ),
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(default=15, limit_choices_to={'usertype': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='certificate',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
