# Generated by Django 5.0.6 on 2024-07-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('visitlog_id', models.AutoField(primary_key=True, serialize=False)),
                ('nfc_uid', models.CharField(max_length=30, null=True)),
                ('enter_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(null=True)),
                ('fields', models.CharField(max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gymmember')),
            ],
        ),
    ]
