# Generated by Django 5.0.4 on 2024-07-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitlogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitlog',
            old_name='fields',
            new_name='QR_fields',
        ),
    ]
