# Generated by Django 5.0.4 on 2024-07-30 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitlogs', '0002_rename_fields_visitlog_qr_fields'),
    ]

    operations = [
    ]
