# Generated by Django 5.0.4 on 2024-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitlogs', '0003_rename_fields_visitlog_qr_fields'),
    ]

    operations = [
    ]
