# Generated by Django 5.0.6 on 2024-07-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_use_time', models.DateTimeField()),
                ('fields', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
