# Generated by Django 5.0.6 on 2024-07-12 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataanalysis', '0001_initial'),
        ('equipment', '0001_initial'),
        ('gyms', '0002_personalinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataanalysis',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gymmember'),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
