# Generated by Django 5.0.6 on 2024-07-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.CharField(max_length=1000, null=True)),
                ('background_color', models.CharField(default='blue', max_length=20)),
                ('pt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gyms.pt')),
            ],
        ),
    ]
