# Generated by Django 5.0.6 on 2024-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_calendar_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
