# Generated by Django 5.0.4 on 2024-07-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_trainerrequest'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gyms.pt'),
        ),
    ]
