# Generated by Django 5.0.6 on 2024-07-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('scheduler', '0002_event_description_event_schedule_calendar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='schedule_calendar_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='pt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gyms.pt'),
            preserve_default=False,
        ),
    ]
