# Generated by Django 5.0.4 on 2024-07-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_event_description_event_schedule_calendar_id'),
        ('scheduler', '0002_remove_event_user_event_description_event_pt'),
    ]

    operations = [
    ]
