# Generated by Django 5.0.4 on 2024-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_merge_20240730_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='schedule_calendar_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
